Traceback (most recent call last):
  File "/home/rm/.cache/pypoetry/virtualenvs/przetwarzanie-danych-zlozonych-kjty6M6D-py3.9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/rm/.cache/pypoetry/virtualenvs/przetwarzanie-danych-zlozonych-kjty6M6D-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/rm/.cache/pypoetry/virtualenvs/przetwarzanie-danych-zlozonych-kjty6M6D-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/rm/.cache/pypoetry/virtualenvs/przetwarzanie-danych-zlozonych-kjty6M6D-py3.9/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/rm/.cache/pypoetry/virtualenvs/przetwarzanie-danych-zlozonych-kjty6M6D-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/rm/.cache/pypoetry/virtualenvs/przetwarzanie-danych-zlozonych-kjty6M6D-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/rm/.cache/pypoetry/virtualenvs/przetwarzanie-danych-zlozonych-kjty6M6D-py3.9/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
library(anytime) 
suppressPackageStartupMessages(library(tidyverse))

# wczytanie
data <- read.csv('data/bike_sharing.csv', header=TRUE, stringsAsFactors=FALSE)

# konwersja stringa na date
data$date <- anydate(data$dteday)

# interesują nas tylko kolumny zawierające datę i liczbę wypożyczonych rowerów
data <- select(data, c("date", "cnt"))

head(data)
------------------

Error in library(anytime): there is no package called ‘anytime’
Traceback:

1. library(anytime)
ERROR: Error in library(anytime): there is no package called ‘anytime’


